# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lets < Formula
  desc "CLI task runner for productive developers - a better alternative to make"
  homepage "https://lets-cli.org/"
  version "0.0.31"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lets-cli/lets/releases/download/v0.0.31/lets_Darwin_x86_64.tar.gz"
    sha256 "719d29922109fff66ecf86530a37ccafbfe8a14055c3580ea51dc636267ead16"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lets-cli/lets/releases/download/v0.0.31/lets_Darwin_arm64.tar.gz"
    sha256 "9d057e9d2edc43e441e802685fd7d4e794b05b6ed144b2b6e501545cab33e10f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lets-cli/lets/releases/download/v0.0.31/lets_Linux_x86_64.tar.gz"
    sha256 "6561fa8f185088f6c752a77e79404e92482b6dfb8d835402b9327d5e1f75b945"
  end

  def install
    bin.install "lets"
  end
end
