# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetsBeta < Formula
  desc "CLI task runner for productive developers - a better alternative to make (prerelease channel)"
  homepage "https://lets-cli.org/"
  version "0.0.63-rc2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lets-cli/lets/releases/download/v0.0.63-rc2/lets_Darwin_x86_64.tar.gz"
      sha256 "7997f5ab008a3af9ce5963869329ef98458894d6994513cd93cc841c97d5020b"

      define_method(:install) do
        bin.install "lets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lets-cli/lets/releases/download/v0.0.63-rc2/lets_Darwin_arm64.tar.gz"
      sha256 "6083e3c7cbbceccc0486b5b456376744ad8ba35101ed4906f9dc974600e0c834"

      define_method(:install) do
        bin.install "lets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lets-cli/lets/releases/download/v0.0.63-rc2/lets_Linux_x86_64.tar.gz"
      sha256 "e502aa276f90bc76e787632135f4d6d1f465bba3c3aaee174a7cabcd542788aa"
      define_method(:install) do
        bin.install "lets"
      end
    end
  end

  conflicts_with "lets"
end
