# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lets < Formula
  desc "CLI task runner for productive developers - a better alternative to make"
  homepage "https://lets-cli.org/"
  version "0.0.58"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lets-cli/lets/releases/download/v0.0.58/lets_Darwin_x86_64.tar.gz"
      sha256 "f75a5488d7dacd89e7becc6d3187207405201555737a8cc4a7e8d8598a0035d6"

      def install
        bin.install "lets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lets-cli/lets/releases/download/v0.0.58/lets_Darwin_arm64.tar.gz"
      sha256 "3f0bf013db30254a7908de04fda88f27ee93caf600100987215293d0fe4ba188"

      def install
        bin.install "lets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lets-cli/lets/releases/download/v0.0.58/lets_Linux_x86_64.tar.gz"
      sha256 "ebce6a49395d6943661235087de311b469a13a0bf182a8222de3d4e4e4197e89"
      def install
        bin.install "lets"
      end
    end
  end
end
